### ISSUE TITLE
Private / Ticket shows (bug and feature request)

### ISSUE THREAD

**Issue by thomaz1342** [beaston02/CamsodaRecorder#2]
Hi @beaston02 

First off, thanks a lot for all your work in building this application, I've got it running now on free cam but Private (spy) doesn't seem to want to start, it briefly lists the name of the model name in private spy in the brackets and then simply resets the counter with no errors displayed:

(I set the reset value at 180)

___________________

0 model(s) are being recorded. Next check in 95 seconds
the following models are being recorded: [name briefly listed here]

_______________________

Any plans to support recording of gold ticket shows at some point?

Thanks again!

Setup:
Mac 10.13.1 Beta
Python 3.6
Livestreamer 1.12.2

**Comment by beaston02** [comment]
Hi! Thanks for the feedback! 

I actually noticed just the other day the the ticket shows were no longer recording. I dont run this script myself, but I was working on it to fix the latest issue where it wasnt getting the online models and noticed some changes with the ticket shows. 

To be blunt about it, they used to have a really stupid setup for their ticket shows. The api call used to get the info for their free shows also reported back the server/stream info for their ticket shows (I believe it was the ticket shows, Im not real familiar with the site, so I may be using the wrong term here). They seemed to change it so they no longer just broadcast that info to everyone (in other words, they wised up some). I did not look into it much to see if/how I could get the paid show streams, but I assume it will now require a login. The reason it is flashing the name then its going away is because some of the reporting is still the same. The script still sees the model as being online, and it lists them as recording as the recording is attempted to start, then it immediately fails and the model is removed from the recording list. This is when you see it there for about a second or so. I should be able to fix it so it doesnt report them as recording until the script has gotten a working stream, but I probably wont do an update just for that. I will most likely wait until I can do a more complete rewrite of the script, including adding in some more options/settings. Until then, you will have to deal with the flashing of the name! 

As far as any plans to record private/paid shows, I do not plan to incorporate that. The main reason is, I have no intentions on buying any tokens/credits/whatever camsoda uses. In order to reverse engineer the site and the stream, I would have to enter a paid show myself and figure out how to gather all the info to build the URL for the stream. Most likely it would be fairly easy to do, but would require creating a login object for the script, because you would need to use your account to get the token/key passed to your username to access the stream. If someone wanted to make a donation, I could use that to look into this, but its not a high priority of mine.

**Comment by ghost** [comment]
@beaston02 how much of a donation? i think me and @thomaz1342 are very interested in this, streamlink is taking too long, id prefer a fix that not only frees up privates and ticket shows, so i dont have to use idm, which freezes/lags sometimes on me, but also catches the stream in the same manner as idm, meaning a slightly higher quality video. when i use idm the video is 848x478, its a little smaller and sometimes pixelated with streamlink. freezing once happened during an actual paid private and i lost 5 minutes out of a 15 minute show. or do you simply need an account to do this? i have several.

**Comment by beaston02** [comment]
I can't say what it would take. Hopefully the solution would jump right out at me. It may be as simple as creating a requests session (similar to how opening a browser and browsing a website works, cookies are retained, you stay logged in, and so on...), logging into that session, and using that session to grab the info from the API. I believe it reports a token (key) for the stream, but I'm going off memory so I may be wrong. If I'm not mistaking, it's very possible that's all that would be needed. I definitely can't guarantee anything, so a donation may go to waste. 

If you want to message me on reddit, I could discuss this further with you. There could also be some other options, which I could go over with you in private. My username on there is beaston02 (same as here).

**Comment by ghost** [comment]
I'll be messaging you shortly

**Comment by thomaz1342** [comment]
Hi @ls117 & @beaston02  Great stuff guys, let me know if I can be of any help.

Thanks again.
